name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Create dummy .env file
        run: touch .env
      - name: Create dummy Firebase options for validation
        run: |
          mkdir -p lib
          cat > lib/firebase_options.dart << 'EOF'
          // Dummy Firebase options for CI validation
          import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
          import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
          
          class DefaultFirebaseOptions {
            static FirebaseOptions get currentPlatform {
              if (kIsWeb) {
                throw UnsupportedError('Web platform not supported');
              }
              switch (defaultTargetPlatform) {
                case TargetPlatform.android:
                  return android;
                case TargetPlatform.iOS:
                  return ios;
                default:
                  throw UnsupportedError('Platform not supported');
              }
            }
          
            static const FirebaseOptions android = FirebaseOptions(
              apiKey: 'dummy-key',
              appId: '1:123456789:android:dummy',
              messagingSenderId: '123456789',
              projectId: 'dummy-project',
              storageBucket: 'dummy-project.appspot.com',
            );
          
            static const FirebaseOptions ios = FirebaseOptions(
              apiKey: 'dummy-key',
              appId: '1:123456789:ios:dummy',
              messagingSenderId: '123456789',
              projectId: 'dummy-project',
              storageBucket: 'dummy-project.appspot.com',
              iosBundleId: 'com.example.marketsnap',
            );
          }
          EOF
          echo "✅ Created dummy lib/firebase_options.dart for validation"
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Install, lint, build, and test functions
        working-directory: ./functions
        run: |
          npm install
          npm run lint
          npm run build
          npm test
      - name: Analyze Flutter project
        run: flutter analyze
      - name: Run Flutter tests
        run: flutter test 