name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Create dummy .env file
        run: touch .env
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Install, lint, and build functions
        working-directory: ./functions
        run: |
          npm install
          npm run lint
          npm run build
      - name: Analyze Flutter project
        run: flutter analyze
      - name: Run Flutter tests
        run: flutter test 