name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Create dummy .env file
        run: touch .env
      - run: flutter pub get
      - run: flutter doctor
      - run: flutter test 