name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Create dummy .env file
        run: touch .env
      - name: Generate firebase.json from template
        env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          ANDROID_APP_ID: ${{ secrets.ANDROID_APP_ID }}
          IOS_APP_ID: ${{ secrets.IOS_APP_ID }}
        run: |
          # Install envsubst if not available
          sudo apt-get update && sudo apt-get install -y gettext-base
          # Generate firebase.json from environment variables
          envsubst < firebase.json > firebase.json.tmp && mv firebase.json.tmp firebase.json
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Install, lint, and build functions
        working-directory: ./functions
        run: |
          npm install
          npm run lint
          npm run build
      - name: Analyze Flutter project
        run: flutter analyze
      - name: Run Flutter tests
        run: flutter test 